"""Add automatic battle configuration

Revision ID: 224b5455822b
Revises: ead2c89fce3f
Create Date: 2026-08-18 18:49:57.636154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ============================================================
# REVISION IDENTIFIERS
# ============================================================

revision: str = "224b5455822b"

down_revision: Union[
    str,
    Sequence[str],
    None,
] = "ead2c89fce3f"

branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None

depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


# ============================================================
# UPGRADE
# ============================================================

def upgrade() -> None:
    """Upgrade schema."""

    # --------------------------------------------------------
    # ASSESSMENT SKILL
    # --------------------------------------------------------

    op.add_column(
        "assessments",
        sa.Column(
            "skill_id",
            sa.Integer(),
            nullable=True,
        ),
    )

    # --------------------------------------------------------
    # ASSESSMENT TOPIC
    # --------------------------------------------------------

    op.add_column(
        "assessments",
        sa.Column(
            "topic",
            sa.String(length=150),
            nullable=True,
        ),
    )

    # --------------------------------------------------------
    # QUESTION COUNT
    #
    # IMPORTANT:
    # Existing assessments already exist in the database.
    #
    # Therefore we MUST provide a server_default while
    # adding this NOT NULL column.
    #
    # Existing assessments will receive question_count = 10.
    # --------------------------------------------------------

    op.add_column(
        "assessments",
        sa.Column(
            "question_count",
            sa.Integer(),
            nullable=False,
            server_default="10",
        ),
    )

    # --------------------------------------------------------
    # INDEXES
    # --------------------------------------------------------

    op.create_index(
        op.f("ix_assessments_skill_id"),
        "assessments",
        ["skill_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_assessments_topic"),
        "assessments",
        ["topic"],
        unique=False,
    )

    # --------------------------------------------------------
    # FOREIGN KEY
    # --------------------------------------------------------

    op.create_foreign_key(
        None,
        "assessments",
        "skills",
        ["skill_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # --------------------------------------------------------
    # USER QUEST UNIQUE CONSTRAINT
    #
    # Preserve the change generated by Alembic.
    # --------------------------------------------------------

    op.drop_constraint(
        op.f("uq_user_quest"),
        "user_quests",
        type_="unique",
    )


# ============================================================
# DOWNGRADE
# ============================================================

def downgrade() -> None:
    """Downgrade schema."""

    # --------------------------------------------------------
    # RESTORE USER QUEST CONSTRAINT
    # --------------------------------------------------------

    op.create_unique_constraint(
        op.f("uq_user_quest"),
        "user_quests",
        ["user_id", "quest_id"],
        postgresql_nulls_not_distinct=False,
    )

    # --------------------------------------------------------
    # DROP ASSESSMENT FOREIGN KEY
    # --------------------------------------------------------

    op.drop_constraint(
        None,
        "assessments",
        type_="foreignkey",
    )

    # --------------------------------------------------------
    # DROP INDEXES
    # --------------------------------------------------------

    op.drop_index(
        op.f("ix_assessments_topic"),
        table_name="assessments",
    )

    op.drop_index(
        op.f("ix_assessments_skill_id"),
        table_name="assessments",
    )

    # --------------------------------------------------------
    # DROP NEW COLUMNS
    # --------------------------------------------------------

    op.drop_column(
        "assessments",
        "question_count",
    )

    op.drop_column(
        "assessments",
        "topic",
    )

    op.drop_column(
        "assessments",
        "skill_id",
    )