"""Add quest system

Revision ID: 5caa9496f17d
Revises: d44ecd366fcb
Create Date: 2026-08-16 10:42:36.497027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5caa9496f17d'
down_revision: Union[str, Sequence[str], None] = 'd44ecd366fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quest_type', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_index(op.f('ix_quests_is_active'), 'quests', ['is_active'], unique=False)
    op.create_index(op.f('ix_quests_quest_type'), 'quests', ['quest_type'], unique=False)
    op.create_table('user_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_user_quest')
    )
    op.create_index(op.f('ix_user_quests_id'), 'user_quests', ['id'], unique=False)
    op.create_index(op.f('ix_user_quests_quest_id'), 'user_quests', ['quest_id'], unique=False)
    op.create_index(op.f('ix_user_quests_user_id'), 'user_quests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quests_user_id'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_quest_id'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_id'), table_name='user_quests')
    op.drop_table('user_quests')
    op.drop_index(op.f('ix_quests_quest_type'), table_name='quests')
    op.drop_index(op.f('ix_quests_is_active'), table_name='quests')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    # ### end Alembic commands ###
