"""add topic to questions

Revision ID: 6ea284375b18
Revises: 347260973fb8
Create Date: 2026-08-14 19:32:59.593981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea284375b18'
down_revision: Union[str, Sequence[str], None] = '347260973fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_column('questions', 'topic')
    # ### end Alembic commands ###
