"""Add skill progress

Revision ID: d44ecd366fcb
Revises: 901563e92635
Create Date: 2026-08-15 12:18:07.114473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44ecd366fcb'
down_revision: Union[str, Sequence[str], None] = '901563e92635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('battles_completed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill_progress')
    )
    op.create_index(op.f('ix_skill_progress_id'), 'skill_progress', ['id'], unique=False)
    op.create_index(op.f('ix_skill_progress_skill_id'), 'skill_progress', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_progress_user_id'), 'skill_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_progress_user_id'), table_name='skill_progress')
    op.drop_index(op.f('ix_skill_progress_skill_id'), table_name='skill_progress')
    op.drop_index(op.f('ix_skill_progress_id'), table_name='skill_progress')
    op.drop_table('skill_progress')
    # ### end Alembic commands ###
